# Generated by Django 2.2.5 on 2021-03-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.IntegerField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('pizza_name', models.CharField(max_length=30)),
                ('order_time', models.IntegerField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margherita', models.CharField(max_length=30)),
                ('salami', models.CharField(max_length=30)),
                ('diavolo', models.CharField(max_length=30)),
            ],
        ),
    ]
